name = "erickshaw-site"
type = "static"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"
